name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ macos-15-intel, macos-26 ]
        include:
          - os: ubuntu-latest
            container: ghcr.io/homebrew/brew:main
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove preinstalled third-party taps
        run: |
          for tap in aws/tap azure/bicep cirruslabs/cli
          do
            brew untap "$tap" || true
          done

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae --testing-formulae=racket@9 --skip-dependents

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
